PREFIX=/usr/local
CXX=gcc
CXXFLAGS=-Wall -Os -pedantic
CPP=g++
CPPFLAGS=-Wall -Os -pedantic

breplace: breplace.c
	${CXX} ${CXXFLAGS} -o ../bin/breplace breplace.c

mb2tap: endian-compat.h mb2tap.c
	${CXX} ${CXXFLAGS} -o ../bin/mb2tap mb2tap.c

mbdir: endian-compat.h mbdir.c
	${CXX} ${CXXFLAGS} -o ../bin/mbdir mbdir.c

mbload: endian-compat.h mbload.c
	${CXX} ${CXXFLAGS} -o ../bin/mbload mbload.c

d802tap: d802tap.cpp
	${CPP} ${CPPFLAGS} -o ../bin/d802tap d802tap.cpp

tap2d80: tap2d80.cpp
	${CPP} ${CPPFLAGS} -o ../bin/tap2d80 tap2d80.cpp

tap2mbd: tap2mbd.cpp
	${CPP} ${CPPFLAGS} -o ../bin/tap2mbd tap2mbd.cpp

tap2mbhdd: tap2mbhdd.cpp
	${CPP} ${CPPFLAGS} -o ../bin/tap2mbhdd tap2mbhdd.cpp

bin2tap: bin2tap.c
	${CXX} ${CXXFLAGS} -o ../bin/bin2tap bin2tap.c

bin2mbd: bin2mbd.c
	${CXX} ${CXXFLAGS} -o ../bin/bin2mbd bin2mbd.c

binto0: binto0.c
	${CXX} ${CXXFLAGS} -o ../bin/binto0 binto0.c

dirtap: endian-compat.h dirtap.c
	${CXX} ${CXXFLAGS} -o ../bin/dirtap dirtap.c

dirhob: endian-compat.h dirhob.c
	${CXX} ${CXXFLAGS} -o ../bin/dirhob dirhob.c

dir0: endian-compat.h dir0.c
	${CXX} ${CXXFLAGS} -o ../bin/dir0 dir0.c

hobto0: endian-compat.h hobto0.c
	${CXX} ${CXXFLAGS} -o ../bin/hobto0 hobto0.c

lstbas: endian-compat.h lstbas.c
	${CXX} lstbas.c ${CXXFLAGS} -lm -o ../bin/lstbas

tapto0: endian-compat.h tapto0.c
	${CXX} ${CXXFLAGS} -o ../bin/tapto0 tapto0.c

tsttap: endian-compat.h tsttap.c
	${CXX} ${CXXFLAGS} -o ../bin/tsttap tsttap.c

0tobin: endian-compat.h 0tobin.c
	${CXX} ${CXXFLAGS} -o ../bin/0tobin 0tobin.c

0tohob: endian-compat.h 0tohob.c
	${CXX} ${CXXFLAGS} -o ../bin/0tohob 0tohob.c

0totap: endian-compat.h 0totap.c
	${CXX} ${CXXFLAGS} -o ../bin/0totap 0totap.c

makesna: makesna.cpp
	${CPP} ${CPPFLAGS} -o ../bin/makesna makesna.cpp

tzx2tap: endian-compat.h tzx2tap.c
	${CXX} ${CXXFLAGS} -o ../bin/tzx2tap tzx2tap.c

tap2tzx: endian-compat.h tap2tzx.c
	${CXX} ${CXXFLAGS} -o ../bin/tap2tzx tap2tzx.c

permutor: permutor.c
	${CXX} ${CXXFLAGS} -o ../bin/permutor permutor.c

lstrd: lstrd.c
	${CXX} ${CXXFLAGS} -o ../bin/lstrd lstrd.c

createtrd: createtrd.c
	${CXX} ${CXXFLAGS} -o ../bin/createtrd createtrd.c

hobeta2trd: hobeta2trd.c
	${CXX} ${CXXFLAGS} -o ../bin/hobeta2trd hobeta2trd.c

